package com.teliolabs.tejas.gpon.dto.inventory;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class PhysicalPort {
    @JsonProperty("NEName")
    private String neName;
    @JsonProperty("otnNeid")
    private String otnNeid;
    @JsonProperty("cardName")
    private String cardName;
    @JsonProperty("PortName")
    private String portName;
    @JsonProperty("PortRate")
    private String portRate;
    @JsonProperty("signalType")
    private String signalType;
    private String commissionedStatus;
    private String oppositeDirectionPort;
    private String pluggableModuleType;
    private String installedPartNumber;
    private String eptDemandName;
    private String oprMode;
    private String frequency;
    private String receiveFrequency;
    private String fectype;
    private String encoding;
    private String waveShape;
    private String monitoredPort;
    private String connectedLDOTDRPort;
    private String ptpioSigPortConnFrom;
    private String ptpioSigPortConnTo;
    private String connectedLineDCM;
    private String connectedLinePort;
    private String minPlannedLossIn;
    private String maxPlannedLossIn;
    private String typicalPlannedLossIn;
    private String minPlannedLossOut;
    private String maxPlannedLossOut;
    private String typicalPlannedLossOut;
    private String actualTilt;
    private String allowedGainDelta;
    private String attenuation;
    private String autoEgressAdjustment;
    private String egressOAPpcOut;
    private String egressRipple;
    private String fiberLength;
    private String fiberType;
    private String forcedPerChannelOutputPower;
    private String gain;
    private String gainMode;
    private String gainTilt;
    private String ingressRippleAllowance;
    private String initialLoss;
    private String initialTargetGain;
    private String inputToOutputGain;
    private String maxAttenuation;
    private String maxGain;
    private String maximumChannelsPerDegree;
    private String minAddChannelPower;
    private String minAttenuation;
    private String minExpressChannelPower;
    private String minGain;
    private String perChannelInputPowerDeviation;
    private String perChannelOutputPower;
    private String perChannelOutputPowerAdjustment;
    private String perChannelOutputPowerDeviation;
    private String portPowerIn;
    private String powerManagementType;
    private String ramanSignalOutputPower;
    private String ramanTotalInputPower;
    private String signalOutputPower;
    private String spanLossDefault;
    private String spliceMargin;
    private String targetGain;
    private String targetTilt;
    private String totalInputPower;
    private String totalOutputPower;
    private String voaSet;
    private String userLabel;
    private String primaryState;
    private String secondaryState;
    private String portIndex;
    private String baseLineReasonOPT;
    private String baseLineReasonOPR;
    private String baseLineValueOPT;
    private String baseLineValueOPR;
    private String baseLineTimeOPT;
    private String baseLineTimeOPR;
    private String transmitPower;
    private String receivePower;
    private String totalOutputPowerL;
    private String signalOutputPowerL;
    private String perChannelOutputPowerL;
    private String perChannelOutputPowerDeviationL;
    private String gainModeL;
    private String gainL;
    private String minGainL;
    private String maxGainL;
    private String allowedGainDeltaL;
    private String targetTiltL;
    private String gainTiltL;
    private String actualTiltL;
    private String inputToOutputGainL;
    private String perChannelInputPowerDeviationL;
    private String phaseEncoding;
    private String totalInputPowerL;
    private String voaSetL;
    private String singleFiberBidi;
    private String singleFiberChannelPlan;
    private String connectedToPort;
    private String gridType;
    private String perChannelInputPower;
    private String gridStepSize;
    private String txFreqOffset;
    private String rxFreqOffset;
    private String oscRxPowerIn;
    private String oscTxPowerOut;
    private String oscTxPowerIn;
    private String connectedOTDRport;
    private String oscSfpTxPowerOut;
    private String oscSfpRxPowerIn;
    private String spanLossTilt;
    private String spanLossTiltL;
    private String autoGainAdjustment;
    private String autoTiltAdjustment;
    private String externalAmp;
    private String measuredLossIn;
    private String commissionedLossIn;
    private String measuredLossOut;
    private String commissionedLossOut;
    private String measuredLossInL;
    private String commissionedLossInL;
    private String measuredLossOutL;
    private String commissionedLossOutL;
    private String typicalPlannedLossInL;
    private String minPlannedLossInL;
    private String maxPlannedLossInL;
    private String typicalPlannedLossOutL;
    private String minPlannedLossOutL;
    private String maxPlannedLossOutL;
    private String encapsulationMode;
    private String subGridModeType;
    private String dcmPresentIn;
    private String attenuationL;
    private String egressOAPowerGainL;
    private String transmissionMode;
    private String inLoop;
    private String outLoop;
    private String portDirection;
    private String portRole;
    @JsonProperty("otsigIdentifier")
    private String otsigIdentifier;
    private String otsigOtuStruct;
    private String cdPreComp;
    private String otsigProfile;
    @JsonProperty("ObjectIdentifier")
    private String objectIdentifier;
    private String linkSpan;
    private String portInfoInsertionLoss;
    private String currentGain;
    private String aprEnabled;
    private String egressConnectorLossToSpan;
    private String aseNoiseMode;
    private String designatedPortMode;
    private String designatedRegenPair;
    private String extraInputLoss;
    private String egressServiceLaunchAttenuationOffset;
    private String alienWaveBank;
    private String aseLLc;
    private String aseLLl;
    private String aseLLlink;
    private String aseLLlinkL;
    private String targetPowerWidth;
    private String targetPowerWidthL;
    private String portManagementMode;
    private String plannedFrequencyIn;
    private String plannedFrequencyOut;
    private String tnVwmMsIfDescr;
    private String addTargetPower;
    private String configDropExpressTargetPower;
    private String expressChannelTargetPower;
    private String expressTargetPower;
    private String sdiRate;
    private String powerManagerSmoothing;
    private String voaCurrent;
    private String refSysProfileId;
    private String baudrate;
    private String monOcmConnAddress;
    private String associatedFirstRoadmTx;
    private String associatedFirstRoadmRx;
    private String associatedSecondRoadmTx;
    private String associatedSecondRoadmRx;
    private String aseOutputPower;
    private String calcSpanLoss;
    private String txfineoffset;
    private String rxfineoffset;
}
